name: Classroom AutoGrading Setup
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student assignment
        uses: actions/checkout@v2
      
      - name: Checkout tests
        uses: actions/checkout@v2
        with:
          repository: ApolloPavilion/caesar_tests
          path: tests
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check50
      - uses: education/autograding@v1
